
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface SitePreferences {
			/**
			* Product Inventory Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Product Inventory Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#5) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#337)
			*/
			brEngProductInventoryFeedDataMapping: string | null;

			/**
			* Variants Inventory Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Variants Inventory Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#18) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#338)
			*/
			brEngVariantsInventoryFeedDataMapping: string | null;

			/**
			* Product Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Product Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#33) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#335)
			*/
			brEngProductsFeedDataMapping: string | null;

			/**
			* Variant Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Variant Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#76) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#336)
			*/
			brEngVariantsFeedDataMapping: string | null;

			/**
			* Customer Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Customer Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#122) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#332)
			*/
			brEngCustomerFeedDataMapping: string | null;

			/**
			* Bloomreach Custom Order Product Properties For Export

				Overrides default data mapping with user-defined custom data mapping for Purchase Item Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#148) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#334)
			*/
			brEngPurchaseItemDataMapping: string | null;

			/**
			* Purchase Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Purchase Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#181) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#333)
			*/
			brEngPurchaseFeedDataMapping: string | null;

			/**
			* Purchase Item Feed (Full Export) From Date

				The orders placed after the configured date will be exported in the Purchase Item Feed (Full Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#206) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#341)
			*/
			brEngPurchaseItemFeedFullExportFromDate: Date | null;

			/**
			* Purchase Feed (Full Export) From Date

				The orders placed after the configured date will be exported in the Purchase Feed (Full Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#213) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#339)
			*/
			brEngPurchaseFeedFullExportFromDate: Date | null;

			/**
			* Bloomreach Date Of Order Export - Purchase_item Feed(NewOrders)

				The orders placed after the configured date will be exported in the purchase product feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#220) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#342)
			*/
			bloomreachPurchaseItemFeedNewOrdersFromDate: Date | null;

			/**
			* Purchase Feed (Delta Export) From Date

				The orders placed after the configured date will be exported in the Purchase Feed (Delta Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#227) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#340)
			*/
			brEngPurchaseFeedDeltaExportFromDate: Date | null;

			/**
			* Customer Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#234) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#352)
			*/
			brEngCustomerFeedImportId: string | null;

			/**
			* Product Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#241) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#355)
			*/
			brEngProductFeedImportId: string | null;

			/**
			* Purchase Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#248) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#353)
			*/
			brEngPurchaseFeedImportId: string | null;

			/**
			* Purchase Item Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#255) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#354)
			*/
			brEngPurchaseItemFeedImportId: string | null;

			/**
			* Variant Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#262) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#357)
			*/
			brEngVariantFeedImportId: string | null;

			/**
			* API Base URL
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#269) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#346)
			*/
			brEngApiBaseUrl: string | null;

			/**
			* API key ID
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#277) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#348)
			*/
			brEngApiKeyId: string | null;

			/**
			* API Key Secret
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#284) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#349)
			*/
			brEngApiKeySecret: string | null;

			/**
			* Project Token
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#291) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#347)
			*/
			brEngProjectToken: string | null;

			/**
			* Product Inventory Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#298) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#356)
			*/
			brEngProductInventoryFeedImportId: string | null;

			/**
			* Variant Inventory Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#305) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#358)
			*/
			brEngVariantInventoryFeedImportId: string | null;

			/**
			* File Download Endpoint Username

				Username for Basic Auth on the controller-based file download endpoint (replaces WebDAV credentials)
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#312) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#350)
			*/
			brEngDownloadUsername: string | null;

			/**
			* File Download Endpoint Password

				Password for Basic Auth on the controller-based file download endpoint (replaces WebDAV credentials)
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#320) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#351)
			*/
			brEngDownloadPassword: string | null;

		}
		interface Product {
			/**
			* Bloomreach Tags

				This attribute is used for adding special tags like new, back in stock to the product
			* @group bloomreachProductAttributes - Bloomreach Product Attributes
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#365) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#380)
			*/
			bloomreachTags: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
					/**
			* Product Inventory Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Product Inventory Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#5) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#337)
			*/
			(name: 'brEngProductInventoryFeedDataMapping'): string | null;
			
			/**
			* Variants Inventory Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Variants Inventory Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#18) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#338)
			*/
			(name: 'brEngVariantsInventoryFeedDataMapping'): string | null;
			
			/**
			* Product Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Product Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#33) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#335)
			*/
			(name: 'brEngProductsFeedDataMapping'): string | null;
			
			/**
			* Variant Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Variant Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#76) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#336)
			*/
			(name: 'brEngVariantsFeedDataMapping'): string | null;
			
			/**
			* Customer Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Customer Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#122) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#332)
			*/
			(name: 'brEngCustomerFeedDataMapping'): string | null;
			
			/**
			* Bloomreach Custom Order Product Properties For Export

				Overrides default data mapping with user-defined custom data mapping for Purchase Item Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#148) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#334)
			*/
			(name: 'brEngPurchaseItemDataMapping'): string | null;
			
			/**
			* Purchase Feed Custom Data Mapping

				Overrides default data mapping with user-defined custom data mapping for Purchase Feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#181) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#333)
			*/
			(name: 'brEngPurchaseFeedDataMapping'): string | null;
			
			/**
			* Purchase Item Feed (Full Export) From Date

				The orders placed after the configured date will be exported in the Purchase Item Feed (Full Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#206) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#341)
			*/
			(name: 'brEngPurchaseItemFeedFullExportFromDate'): Date | null;
			
			/**
			* Purchase Feed (Full Export) From Date

				The orders placed after the configured date will be exported in the Purchase Feed (Full Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#213) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#339)
			*/
			(name: 'brEngPurchaseFeedFullExportFromDate'): Date | null;
			
			/**
			* Bloomreach Date Of Order Export - Purchase_item Feed(NewOrders)

				The orders placed after the configured date will be exported in the purchase product feed
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#220) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#342)
			*/
			(name: 'bloomreachPurchaseItemFeedNewOrdersFromDate'): Date | null;
			
			/**
			* Purchase Feed (Delta Export) From Date

				The orders placed after the configured date will be exported in the Purchase Feed (Delta Export)
			* @group BloomreachEngagement - Bloomreach Engagement
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#227) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#340)
			*/
			(name: 'brEngPurchaseFeedDeltaExportFromDate'): Date | null;
			
			/**
			* Customer Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#234) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#352)
			*/
			(name: 'brEngCustomerFeedImportId'): string | null;
			
			/**
			* Product Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#241) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#355)
			*/
			(name: 'brEngProductFeedImportId'): string | null;
			
			/**
			* Purchase Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#248) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#353)
			*/
			(name: 'brEngPurchaseFeedImportId'): string | null;
			
			/**
			* Purchase Item Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#255) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#354)
			*/
			(name: 'brEngPurchaseItemFeedImportId'): string | null;
			
			/**
			* Variant Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#262) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#357)
			*/
			(name: 'brEngVariantFeedImportId'): string | null;
			
			/**
			* API Base URL
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#269) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#346)
			*/
			(name: 'brEngApiBaseUrl'): string | null;
			
			/**
			* API key ID
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#277) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#348)
			*/
			(name: 'brEngApiKeyId'): string | null;
			
			/**
			* API Key Secret
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#284) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#349)
			*/
			(name: 'brEngApiKeySecret'): string | null;
			
			/**
			* Project Token
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#291) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#347)
			*/
			(name: 'brEngProjectToken'): string | null;
			
			/**
			* Product Inventory Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#298) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#356)
			*/
			(name: 'brEngProductInventoryFeedImportId'): string | null;
			
			/**
			* Variant Inventory Feed Import Id
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#305) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#358)
			*/
			(name: 'brEngVariantInventoryFeedImportId'): string | null;
			
			/**
			* File Download Endpoint Username

				Username for Basic Auth on the controller-based file download endpoint (replaces WebDAV credentials)
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#312) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#350)
			*/
			(name: 'brEngDownloadUsername'): string | null;
			
			/**
			* File Download Endpoint Password

				Password for Basic Auth on the controller-based file download endpoint (replaces WebDAV credentials)
			* @group BloomreachEngagementApi - Bloomreach Engagement API
			* @source [attribute](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#320) | [group](file:/home/tomas/bloomreach/bloomreach-salesforce-commercecloud-b2c-integration/metadata/site-template/meta/system-objecttype-extensions.xml#351)
			*/
			(name: 'brEngDownloadPassword'): string | null;
			
	}
}